name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
  release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Start CI build"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multibuilder
          docker buildx use multibuilder
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BUILD_VERSION=${{ github.event.inputs.version }} \
            -t ghcr.io/bobbyquantum/jackett-addon:${VERSION} \
            -t ghcr.io/bobbyquantum/jackett-addon:latest \
            ./jackett --push
